### ISSUE TITLE
Update bokeh version to 3

### ISSUE THREAD

**Issue by dachengx** [XENONnT/straxen#1206]
`bokeh` has released their version 3 for a while https://pypi.org/project/bokeh/. It takes some time to fix the discrepancy between straxen code and the newest bokeh.

**Comment by cfuselli** [comment]
Hey @dachengx @FaroutYLq,
I had a quick look at this and updating versions of `panel` and `holoviews` seems sufficient to solve the discrepancies. 

In particular:

```
bokeh==3.1.1 (previously 2.4.3)
panel==1.2.0 (previously 1.15.4)
holoviews==1.16.0 (previously 0.14.3)
```

I am running the straxen tests now and seems like they don't raise bokeh related errors anymore. 
I believe that bumping panels and holoviews will not create additional problems.. 

Let me know what you think.

Best,
Carlo

**Comment by cfuselli** [comment]
Ok I failed, there is one issue with .opts and .options in holoviews that I can't fix atm. Will have a look another day maybe.

**Comment by dachengx** [comment]
> Ok I failed, there is one issue with .opts and .options in holoviews that I can't fix atm. Will have a look another day maybe.

Thanks, @cfuselli . That is exactly I am concerned about. No hurry, this is not urgent.

**Comment by JYangQi00** [comment]
I have a minor update on this issue. Basically, I was able to get the `event_display_interactive` function to work with plot_record_matrix=False using bokeh version 3.2.1 along with some modifications to the event display. However, I run into what seems to be some backwards compatibility issues when plot_record_matrix=True. Here is a summary:

- Using bokeh version 3.2.1, panel version 1.2.1, and holoviews version 1.17.0 (i.e. the most updated versions of each package up until 8/8/2023), I get the error:
 ```ValueError: Calling the .opts method with options broken down by options group (i.e. separate plot, style and norm groups) has been removed. Use the .options method converting to the simplified format instead or use hv.opts.apply_groups for backward compatibility.``` which is due to the internal function calls within holoviews
 - Using holoviews version 1.15.4 runs into the issue where `hv.extension('bokeh')` does not properly load the `arrow_heads` model from bokeh, because this has been changed to `arrowheads`

**Comment by WenzDaniel** [comment]
Hej guys thanks for checking. I think it is good that more people are staring to dig into holoviews and bokeh (but holoviews in particular). We can certainly develop more cool tools using these packages. I always wanted to setup an online monitor server at LNGS which would allow us to make interactive online monitor plots. But, I never had and probably never will have the time to look into this. However, I think setting something like this up would be super beneficial.  I need to implement some fixes for the holoviews display anyhow. I will also try to solve the issue.
