### ISSUE TITLE
S1 aft bigger than 1

### ISSUE THREAD

**Issue by GiovanniVolta** [XENONnT/straxen#442]
I observed some events with area fraction top slight greater than one.
For instance, consider **event_info**  of run 012126, s1_area_fraction_top 1.0000001192092896 (index: 1463 ).
I guess it is due to the fact that area_fraction_top is **numpy.float32**

Looking at **peaks** level and selecting this event ((peaks['time'] >= 1611682557517630560) & (peaks['time'] <= 1611682557517631090)). We have:

- area_top = 9.05191
- area_tot = 9.051909

A solution can be:
```
r['area_fraction_top'][m] = area_top[m].astype('f2')/check['area'][m].astype('f2')
```
 I am working with:
```
strax 0.14.0 /dali/lgrandi/strax/strax/strax/__init__.py
straxen 0.17.0 /dali/lgrandi/strax/straxen/straxen/__init__.py
```

**Comment by jingqiangye** [comment]
Thanks @GiovanniVolta . Indeed `area_top` is np.float32 (this [line](https://github.com/XENONnT/straxen/blob/master/straxen/plugins/peak_processing.py#L76)) while the total area `area` is more complicated but looks to have better precision (these [lines](https://github.com/XENONnT/straxen/blob/master/straxen/plugins/peaklet_processing.py#L377-L388)). The different precisions of these two lead to some `area_fraction_top` that are slightly larger than 1.

**Comment by jorana** [comment]
@GiovanniVolta @jingqiangye, thanks for spotting this issue! Both `area_per_channel` and `area_fraction_top` are `np.float32` (see reference from Jingqiang and [the peakdtype](https://github.com/AxFoundation/strax/blob/master/strax/dtypes.py#L191-L192). I think the issue is that there might be an every so slightly negative area in the bottom that makes the `area_fraction_top` go to values >1.

My guess the biggest issue with aft >1 is that it does not pass a trivial aft>1 cut?

**Comment by GiovanniVolta** [comment]
> My guess the biggest issue with aft >1 is that it does not pass a trivial aft>1 cut?
The binomial test B(n, k, p), where n is the S1*S1_AFT, k is S1 and p is AFT (from map), wants n<=k. Otherwise, it fails.
So either I change the cut or we modify the aft at peak level.

**Comment by jorana** [comment]
Right, this is valid. So in principle, your solution is a fine one, with the downside that we are throwing away some precision and then casting it back into a float32. 

Perhaps a simpler and more complete solution would be to clip the AFT as follows:
### Original
```python
        area_top = p['area_per_channel'][:, :n_top].sum(axis=1)
        # Negative-area peaks get NaN AFT
        m = p['area'] > 0
        r['area_fraction_top'][m] = area_top[m]/p['area'][m]
        r['area_fraction_top'][~m] = float('nan')
```
### Changed
(could also do this on `r['area_fraction_top']` but then we need to take care of the NaNs separately).
```python
        area_top = p['area_per_channel'][:, :n_top].sum(axis=1)
        # Don't allow the AFT to be >1
        area_top = np.clip(area_top, 0, p['area'])
        # Negative-area peaks get NaN AFT
        m = p['area'] > 0
        r['area_fraction_top'][m] = area_top[m]/p['area'][m]
        r['area_fraction_top'][~m] = float('nan')
```

**Comment by jingqiangye** [comment]
@jorana I agree that peaks with AFT apparently larger than 1 have negative values in the bottom PMT array, but not so for peaks with AFT slightly larger than 1. The latter still looks like a numerical issue to me. For instance, for the peak @GiovanniVolta points out:

```
>>> peaks = st.get_array("012126", "peaks", keep_columns=["time", "area", "area_per_channel"])
>>> mask_peak = (peaks["time"] >= 1611682557517630560) & (peaks["time"] < 1611682557517631090)
>>> peaks["area_per_channel"][mask_peak][:,:253].sum(axis=1)
array([9.05191], dtype=float32)
>>> peaks["area_per_channel"][mask_peak].sum(axis=1)
array([9.05191], dtype=float32)
>>> peaks["area"][mask_peak]
array([9.051909], dtype=float32)
```
where we have the discrepancy with `area` from these two methods:

- `area` = 9.051909 PE (stored in `peak`)
- `area` = 9.05191 PE (sum of `area_per_channel`)

It seems the `area` stored in the `peak` is calculated in a different way than the sum of `area_per_channel`, which we used to calculate the `area_top` to obtain the `area_fraction_top`. Do we know what causes this discrepancy?

For low-energy events, it is still possible to have all hits in the top PMT array given its large fluctuation, so events with s1_aft=1 could still be real events; but if s1_aft is slightly larger than 1 (even 1.0000001), then it would be removed. Of course we can also modify the cut, but it would better to fix this at peak level.

**Comment by GiovanniVolta** [comment]
I agree with @jingqiangye, it looks like we are computing are in 2 different way. I can provide more example if you want.
Talking about change the cut, what I could do is implement the clip the @jorana  suggest.

**Comment by jorana** [comment]
@GiovanniVolta @jingqiangye , thanks for the details, the problem is clearer now indeed. I'm not sure what the best way forward is. The area is computed actually on many different places:
1. https://github.com/AxFoundation/strax/blob/master/strax/processing/peak_building.py#L250
2. https://github.com/XENONnT/straxen/blob/master/straxen/plugins/peaklet_processing.py#L377-L388
3. https://github.com/AxFoundation/strax/blob/master/strax/processing/peak_merging.py#L63
4. Probably forgot some

So it might be worth checking:
- Was this peak saturated
- Were these multiple peaklets
- What is the peak-type

By the way, Giovani's solution might cause issues as we will run into overflows for large peaks:

```python
>>> np.finfo('f2')
finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)
```

**Comment by jingqiangye** [comment]
@jorana that sounds good to me. So start to use `p["area"] = p["area_per_channel"].sum(axis=1)` at `peaklets` level to make it consistent from the very beginning, or recompute the `area` only at a later stage, say `peak_basics` when `area_fraction_top` appears for the first time? (please correct me if am wrong for any of the statements..)

**Comment by jorana** [comment]
yeah, so the latter as the `peaks/peaklet['area']` is recomputed (potentially) several times and if it is due to numerical rounding errors, it might be best to just do it at `peak_basics` where the last occurrence of any such calculations is involved.

Additionally although inferior, doing it at peaklets would take a lot of time to recompute as it is an intense reprocessing.
