### ISSUE TITLE
Default corrections (for full-chain simulation)

### ISSUE THREAD

**Issue by ramirezdiego** [XENONnT/straxen#478]
At the moment, these lines:
https://github.com/XENONnT/straxen/blob/3913577586b374cd26a3c8bd53787094cf38a7ab/straxen/contexts.py#L53-L57
together with these:
https://github.com/XENONnT/straxen/blob/3913577586b374cd26a3c8bd53787094cf38a7ab/straxen/contexts.py#L192-L203
aim at providing with a simulations context that doesn't rely on CMT defaults.

These only correct for electron lifetime and gain model defaults, therefore a full-chain run beyond `event_basics` would still fetch the straxen defaults for each plugin. In case we want to point CMT to a particular run for our corrections, we have now the tools to do it (see https://github.com/XENONnT/straxen/pull/443 and [these lines](https://github.com/XENONnT/mc_chain/blob/82cb5300f24ec9685a7b420233454b4be18c8d65/run_wfsim.py#L113-L126)).

But as a default we (probably) don't want to use CMT at all and apply custom correction instead. For this we/I should update `xnt_simulation_config` to the point in which we define a non-CMT default for each single correction. Thoughts?

**Comment by jorana** [comment]
Hi Diego, 
So breaking down your proposal, you would:
1. Remove all options where CMT is the defaults and set it to some "reasonable number"
2. Combine all the CMT options into one immutable, which we use for xenonnt_online but not for simulation.

This would be slightly different from what we are currently doing (as much as possible):
- Set the nT defaults as much as possible at the plugin-option level.
- Set 1T/simulations options, different from nT in the context using the appropriate dict.

In principle, I'm fine with your proposal if I understood it right. In fact, there might be two additional advantages of this: 
1.  Make the [testing config used here](https://github.com/XENONnT/straxen/blob/master/tests/test_plugins.py#L17-L36) a bit simpler. Now, for each option that would be pulled from the database (e.g. CMT), we need to specify some offline counterpart. Of course, such a change would not affect e.g. neural nets that are only available in our database.
2. Make the way for a CMT global version v1-context slightly simpler (CMT guys would call this "an offline context"). One would just pull the global version dict (mentioned at 2. above) from CMT instead of using the one as written down in the context.py file for the online-context.

There are two downsides however. There would be a political debate of what numbers to put then as defaults for nT (simulation) which we were avoiding using CMT. Additionally, we were trying to keep the nT defaults next to the plugins as much as possible for readability of the code (was not always possible).

**Comment by ramirezdiego** [comment]
Hey Joran, you got it right. Thanks a lot for explaining the bigger picture in a more educational way than my initial post. This is triggered by my concernt about not having full control of this options in the current simulations context (which makes the average user's life and bookeeping harder); but indeed the bigger issue raised here is how to set the nT defaults in a way that we flexibilize both ends, data processing and simulations, but the plugin code stays readable.

As you say, the simplest solution to not alter the current straxen format is to list all possible corrections in a dense simulations container, in which we need to debate which defaults to set (!). But, as you also imply, this is a good opportunity to rethink the current policy for the default corrections in the plugins and how to keep better track of these via context. This chat could have probably happened earlier, but the MC team was a bit behind the straxen+CMT development, sorry about that.

I'll think about this in the next couple of days and put the ACs in copy, for your last paragraph.

**Comment by ramirezdiego** [comment]
I think we're good with https://github.com/XENONnT/straxen/pull/555 and the cutax-for-contexts approach, so I will close this issue.
Thanks @joran @ershockley and others for the feedback here. Please reopen if you feel there are still open ends.
