### ISSUE TITLE
Add effective livetime calculation to straxen.select_runs

### ISSUE THREAD

**Issue by cwittweg** [XENONnT/straxen#744]
At the moment the select_runs function includes a livetime column in the returned dataframe. I understand that this is the naive live time estimate from the duration of the run. It would be very handy for later analysis to have an effective livetime column that accounts for livetime loss due to cuts right here.

**Comment by JoranAngevaare** [comment]
Hi @cwittweg , after thinking about this a bit more, I'm not sure if we could do that easily within straxen, firstly because it depends on cutax, but more importantly, it also requires having the cut-data you request to be stored.

I think it's probably easiest to do this outside of straxen with something like:
```python
runs = st.select_runs()
runs['effective_live_time'] = [some_function_to_calculate_that_livetime(r_id) for r_id in runs['name']]
```

If you agree, I would close this issue.

**Comment by cwittweg** [comment]
Hi Joran. I see. We can then just do it outside of straxen and find a solution as in XENON1T.
