### ISSUE TITLE
Plugin options could be streamlined

### ISSUE THREAD

**Issue by ershockley** [XENONnT/straxen#784]
Right now the default options of our plugins vary from e.g. online CMT corrections (so nT) and old 1T corrections from when straxen first was developed. I think it might be nice at some point to have all defaults be somewhat consistent, ideally with a focus towards nT over 1T. 

I also would be inclined to move to the [descriptor config](https://github.com/AxFoundation/strax/pull/550) format for specifying options, but that's just a personal opinion. 

This is somewhat related to #328. 

Super low priority of course.

**Comment by JoranAngevaare** [comment]
I agree 👍 . Just to explain what the current state is:
 - Set default values for nT, any divergences with 1T should go in the [1T common config](https://github.com/XENONnT/straxen/blob/64bd823a11800ab7d554b5aedc4114dbfd61cfbf/straxen/contexts.py#L422)
 - However, due to the fact that 1T uses per run defaults and we had this issue https://github.com/AxFoundation/strax/issues/400 with that, some options are overwritten in the [**nT** common config](https://github.com/XENONnT/straxen/blob/64bd823a11800ab7d554b5aedc4114dbfd61cfbf/straxen/contexts.py#L33). Ideally, that config should not be there (which is the same as saying that defaults have to reflect nT).

Before the recently added [descriptor config](https://github.com/AxFoundation/strax/pull/550), there wasn't really much we could do about the per_run_defaults options used for 1T.
