### ISSUE TITLE
get_cmt_options() fails when some CMT options are evaluated at plugin initialization

### ISSUE THREAD

**Issue by jmosbacher** [XENONnT/straxen#938]
**Describe the bug**
Looks like this is an issue with the "get_cmt_options" function for url configs, using the string 'norunids!' as a test to verify that the name of the correction doesnt depend on the run_id. 
This works fine when all configs are were evaluated at runtime, eg when all configs are URLConfigs, but fails when some of the configs are CMT corrections evaluated at plugin initialization in the setup() method because ' norunids!' is not a valid run id. 

I think just changing this test runid to eg '0000' would probably fix this. 

**To Reproduce**
see [PR916](https://github.com/XENONnT/straxen/runs/5360518617?check_suite_focus=true#step:11:235)

**Expected behavior**
Mixing URLConfig and old style CMT options should work without any issues.

**Comment by ershockley** [comment]
Looking at this a bit more I think this is quite dangerous right? It means that something is wrong because a plugin needs to have a run number in order to use CMT -- if you hit this `norunids` error that means there is an error in the config. With this PR instead of catching that error we could be using wrong correction maps. 

Or am I still not understanding?

**Comment by jmosbacher** [comment]
I think thats by design, since CMT needs to have a run number to know what data to fetch. Whether CMT is called on plugin initialization or in the compute method is of course up to the plugin developer. I think sometimes it makes sense to evaluate at initialization but the default behavior of URLConfig is to evaluate at runtime to try to minimize these issues.

**Comment by jmosbacher** [comment]
In any case an alternative approach would be to have CMT return None when a non-existing run is requested

**Comment by ershockley** [comment]
Yeah but what I mean is that there seems to be a bug somewhere that we are shoving under the rug and then just setting e.g. the AFT map to be given the value at run = '0000' if we set that at the default. I think we should understand why exactly it is breaking before assigning a default value (especially a default being run 0)

**Comment by jmosbacher** [comment]
Well I wouldnt call it a bug, since you are setting the run id to a constant just to be able to evaluate the CMT name of the config in case it depends on some other plugin attribute right? so the run id you use for this shouldn't matter.
I agree that the check whether the run id appears in the resulting name is not a very good check on whether the name depends on the run id. Maybe a better test would be to evaluate it for multiple run ids and requiring all values to be the same.
I could make a PR for that if you think it makes sense

**Comment by ershockley** [comment]
Okay yeah I see what you mean. What you propose might be better but I don't think there's really a way to know beforehand what runids might change the config option since CMT is supposed to be separate from straxen. It's tricky. 

Do you think we could maybe add a hack to `event_pattern_fit` instead of `get_corrections`? This is not a problem for this particular plugin but I worry that it could be an issue in the future if we modify it at the `get_corrections` level.

**Comment by jmosbacher** [comment]
Just to be clear, im proposing changing the part in `get_cmt_options` where if its a URL config that uses cmt you load the plugin to evaluate the non cmt part of the URL so you can get the actually cmt name of the config. I dont think we would have to touch `get_corrections` at all

**Comment by ershockley** [comment]
Right, `get_corrections.get_cmt_options`
