### ISSUE TITLE
Add installation paths at logging startup

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/straxen#952]
Like https://github.com/AxFoundation/redax/pull/90, it might be nice to add this new feature to bootstrax' logging too https://github.com/XENONnT/daqnt/pull/85

**Comment by JoranAngevaare** [comment]
@mflierm would you want to have a look - see if we can add this?

**Comment by mflierm** [comment]
@JoranAngevaare Made a first attempt (see version_logging branch). The log now looks like this. Is there any way to make it prettier (use multiple lines, distinguish between lines, etc)?

![Schermafbeelding 2022-04-26 om 16 38 22](https://user-images.githubusercontent.com/53177596/165328566-944b3b6b-a285-4c18-8f55-ebef77a26f66.png)

p.s. It took me ages since I overlooked the 'return_string' argument of `print_versions()`, so I was making all kinds of nice `pd.DataFrame.to_string()` configurations myself haha.

**Comment by JoranAngevaare** [comment]
Looks good!
