### ISSUE TITLE
Set context configs explicitly instead of relying on defaults

### ISSUE THREAD

**Issue by jmosbacher** [XENONnT/straxen#955]
This came up when discussing the issue #937 was meant to solve with @l-althueser. We rely heavily on default values for configs, set in the plugin code. This makes it a bit hard for people to debug these kind of issues since the config values are not all in one place. An extra bonus we would get by having all the config values set explicitly in contexts.py would be avoiding having to hunt down which plugins use a config in straxen, cutax and wfsim whenever you want to change the default value.

**Comment by ershockley** [comment]
I just want to say I fully agree with this!

**Comment by JoranAngevaare** [comment]
Right, just to add since it seems people don't know about it. This is all documented in the https://straxen.readthedocs.io/en/latest/reference/datastructure_nT.html
see e.g.
![afbeelding](https://user-images.githubusercontent.com/22295914/156228460-46bd1e70-7f37-47b9-8c7e-b04c2c74ce5d.png)

now of course, cutax isn't properly documented

It's also trivial to retrieve in cutax-contexts if needed
![afbeelding](https://user-images.githubusercontent.com/22295914/156229192-86d9d484-2ab2-4a87-a04c-65da78d7ef61.png)

**Comment by jmosbacher** [comment]
@JoranAngevaare you are right of course.
But I still think it would be nice to have them all set explicitly and not use defaults.

**Comment by JoranAngevaare** [comment]
Sure, but the comment holds either way 😉. Both your issues are easily resolved using the available tools.

Nevertheless, although I definitely see your point in this issue, I have a slightly different view on this:
- I think the real issue in #937 is that applying global versions is quite clunky now since CMT0 doesn't know about straxen options and relies on the formats we have for options in order to see if it's CMT compatible. I look forward to CMT2 just knowing about what options to apply irrespective if it was a CMT option before.
- I don't think it's very useful to actually have all the options of `pema` ,`nton`, `cutax`, `straxen` etc in one place. It would require going back and forth many times each time you want to update something. In the end, you might end up with _more_ rather than fewer places you need to check. Development would also be even clunkier as you might end up having to make a pr to `corrections`, `private_nt_aux_files`, `cutax`, `straxen` just to add a single feature.
- For code clarity it's better to have the option where they are actually used.
- I'd like to prevent ending up with having multiple huge dictionaries like we have for WFSim (https://github.com/XENONnT/private_nt_aux_files/blob/master/sim_files/fax_config_nt_design.json etc)

That being said, I think this is one of these things where there are definitely pros cons to either argument.

**Comment by jmosbacher** [comment]
Ok, I think you have convinced me.

**Comment by ershockley** [comment]
I just want to say I'm not convinced. The interplay of mixing context options across private and public repos adds additional (and unnecessary I think) confusion, and further we define e.g. simulation contexts in straxen even though wfsim is not a dependency which has never made much sense to me. 

Our context bookkeeping needed for data management is done fully in cutax, so it makes the most sense to me to define _all_ contexts there. I would just hardcode everything to be as clear as possible. 

I don't think it's worth changing right now, but I think at some point it's worth considering this option.
